### PR TITLE
Add buildkite support

### PR DESCRIPTION
**Pull request by trevorbernard**
Fixes: https://github.com/Granola-Team/mina-block-explorer/issues/26

Use just to manage build, etc.

### CODE REVIEW

**Comment by trevorbernard** [comment]
@robinbb I did the legwork but I'll need you to see where I'm going wrong

**Review by robinbb — APPROVED** [review]
'just test-ci' requires 'just lint' and 'just test-e2e' to succeed.
'just lint' fails on my machine.
'just test-e2e' fails, too - no 'npx'. Probably, you should add 'nodejs_18' to the list of buildInputs in flake.nix. Though, you will then have the problem that there is no package-lock.json file (required by 'npm ci').

**Comment by robinbb** [comment]
@trevorbernard I think that the settings on the Buildkite did not previously allow for building pull requests sourced from external (forked) repos. I have adjusted that setting. Try pushing some commits, to see if it's working?

**Comment by trevorbernard** [comment]
> 'just test-ci' requires 'just lint' and 'just test-e2e' to succeed. 'just lint' fails on my machine. 'just test-e2e' fails, too - no 'npx'. Probably, you should add 'nodejs_18' to the list of buildInputs in flake.nix. Though, you will then have the problem that there is no package-lock.json file (required by 'npm ci').

Yeah I'm aware of the lint failing. I wanted the CI to tell me it failed before I made the simple fix. I'll add the nodejs_18 to the build inputs

**Pull request merged**
