### PR TITLE
chore: add .envrc to gitignore

### PR DESCRIPTION
**Pull request by jhult**

### CODE REVIEW

**Comment by robinbb** [comment]
But the .envrc is not to be ignored? We check it in. We change it as needed. Maybe you're thinking of the .env file?

**Comment by jhult** [comment]
> But the .envrc is not to be ignored? We check it in. We change it as needed. Maybe you're thinking of the .env file?

@robinbb,

https://www.toptal.com/developers/gitignore/api/direnv recommends to ignore `.envrc`. More details [here](https://github.com/direnv/direnv/wiki/Git) and [here](https://github.com/toptal/gitignore/pull/241).

**Comment by robinbb** [comment]
That second document says ".gitignore .env, but commit .env{rc,.sample,*} files; see [Git Tips](https://github.com/direnv/direnv/wiki/Git)". It does not say to ignore .envrc. Also, even if it did, I would argue with it. The .envrc is intended to convey how to configure the developer environment so that all devs are working from same premise.

**Comment by jhult** [comment]
Since I don't have strong feelings on this, and since the https://github.com/direnv/direnv wiki has conflicting info, I'm going to close this.

**Pull request closed without merging**
