### PR TITLE
fix: limit from i64 -> u64

### LINKED ISSUE #600: Graphql `load_data` limits are not unsigned
Since we can't return a negative limit the type should be unsigned. Use `u32` or `u64` instead of `i32` or `i64`.

### PR DESCRIPTION
**Pull request by jhult**
u16 has a range from 0 to 65,535. This should be plenty for a limit.

Fixes #600

### CODE REVIEW

**Comment by robinbb** [comment]
I manually canceled the build.

**Comment by robinbb** [comment]
Actually, we may not want to limit the limit to merely 16 bits, on some of these. There may be, in the future, some sort of limit on the limits, but we probably don't want our code to be limited by bits.

**Comment by trevorbernard** [comment]
u16 is too small. There are more accounts than the size of u16. Really ulimit should be usize

**Comment by jhult** [comment]
> u16 is too small. There are more accounts than the size of u16. Really ulimit should be usize

There are more accounts than u16 (65,535). However, for a limit on querying these, `u16` is already more than the (1000) we support...

**Comment by robinbb** [comment]
I'm saying that while there should be a limit, that limit should be specified as a constant somewhere (probably compile time, but could even be runtime), and I wouldn't want that to be limited to 2^16. Only the front-end needs a low limit. Recal that the indexer may serve as a back-end for a variety of uses, not merely to satisfy the in-browser front-end.

**Comment by n1tranquilla** [comment]
Much of the underlying graphql generated code assumes i64. That's why you see casting back to i64 in some of the function.rs files. This is somewhat unavoidable, given the limitations of the library.

**Comment by n1tranquilla** [comment]
Re-running the tests since they have stabilized recently.

**Comment by robinbb** [comment]
I think that @jhult intends to close this PR, splitting into 2+ others.

**Review by robinbb — APPROVED** [review]

**Comment by jhult** [comment]
I found the issue. I was using `.unwrap_or_default() as i64` and this was defaulting to 0 in some cases instead of what I actually wanted (`None`). Now I'm using `.map(|x| x as i64)`.

**Comment by robinbb** [comment]
@jhult Best to make CI go green before merging.

**Pull request merged**
