### PR TITLE
Test username is showing consistently between pages

### PR DESCRIPTION
**Pull request by n1tranquilla**
Closes: Granola-Team/mina-indexer#1067

### CODE REVIEW

**Comment by robinbb** [comment]
So, the test is failing. Is the test wrong, or is the feature not present?

**Comment by n1tranquilla** [comment]
The test is failing because the feature is not yet present. TDD

**Comment by n1tranquilla** [comment]
The feature is present... Retesting....

**Comment by trevorbernard** [comment]
Usernames show up in the accounts page: https://minasearch.com/addresses/accounts?q-public-key=B62qq3tqfdj19hqaVCozJFM2q9gT2WezQMaJMKD6wxyvK3fMpHiP9va

**Comment by n1tranquilla** [comment]
@trevorbernard test is showing the same 

Screen Shot 2024-06-11 at 2 25 22 PM

**Review by robinbb — APPROVED** [review]

**Pull request merged**
